### ISSUE TITLE
Support new Range values from BCDAMS-MAP

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/brays#12]
BCDAMS-MAP will put range_label and range_url in as a array. Brays will need to make adjustments to this change.

https://github.com/uhlibraries-digital/bcdams-map/issues/26

**Comment by metaweidner** [comment]
Revised BCDAMS-MAP range template including values for drop down menus. Range may contain multiple elements with the `uri` attribute but only one element with a `values` attribute (for drop down menus).

`
"range": [
	{
		"label": "",
	 	"uri": ""
	},
	{
		"label": "",
	 	"values": [
			"",
			""]
	}
],
`
