### ISSUE TITLE
Typeahead for a SKOS Collection

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/brays#14]
Can the Brays typeahead get values limited to a specific collection in Cedar? The Genre field will most likely be a subset of the Concept class identified by a collection:

- https://uhlibraries-digital.github.io/bcdams-map/#hasType
- https://vocab.lib.uh.edu/en/collections/aat.html

**Comment by seanlw** [comment]
Collections are handled differently in Cedar. Brays only pulls from the hierarchy.ttl file to get the full list of concepts. This is the only option within the API to get any hierarchy information along with all the prefLabels. This is how Brays limits values based off the Range label (not the uri).

Collection is only a list of references. Brays could mash that with the full hierarchy information, but Brays will need to know it's a collection to get the information and what to do with it for typeahead to work.

I think we need to build a more robust API in Cedar to handle all these use-cases with Brays and other applications.

**Comment by metaweidner** [comment]
The Cedar API enhancements could possibly take the form of a Linked Data Fragments interface.

**Comment by seanlw** [comment]
I would like to move this discussion into Cedar to improve its API to address requests like these. We can open up more issues in Brays once new APIs become available.

https://github.com/uhlibraries-digital/cedar/issues/13
