### ISSUE TITLE
Add "Open File" button to form page?

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/brays#17]
Are we able to add an "Open File" button to the metadata entry form page? (vs. clicking on the image file and clicking the button from that screen)

**Comment by seanlw** [comment]
What happens when you have multiple files to a object? Opening directories isn't possible yet in the Electron version used in Brays. Furthermore, what happens if the files are not in the same directory? This won't happen for us, but what about another institution using Brays.

**Comment by seanlw** [comment]
@amgaynor Is this still a valid feature request? If not, please close.
