### ISSUE TITLE
Display Natural Language Date

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/brays#21]

**Comment by seanlw** [comment]
Validate EDTF is already covered in Issue #7

**Comment by seanlw** [comment]
How do you see this display working?

**Comment by metaweidner** [comment]
@seanlw Thanks for updating the issue title. I see it using something like https://github.com/inukshuk/edtf-ruby to display what the date will look like to end users after the object has been ingested into the repository.

**Comment by seanlw** [comment]
@metaweidner Are we assuming Hyku will display a NLD? Anyway, I'm guessing showing some preview text below the metadata field might work to show what it will look like.

Will this be limited to `dc.date` or any field with a name `date`?

**Comment by seanlw** [comment]
@metaweidner confirmed we will only be addressing `dc.date`. The idea is to have the NLD be displayed under the field to help metadata creators create dates.

**Comment by seanlw** [comment]
@amgaynor Moving your comment here. @metaweidner Here is the example I mentioned in the stand up:
https://github.com/duke-libraries/edtf-humanize

**Comment by seanlw** [comment]
@amgaynor Thanks. I'll start looking at this so I can re-write it for Brays

**Comment by amgaynor** [comment]
Great! It's possible that some of the text we decide upon will be different (e.g "approximately" instead of "circa"), but we'll be sure to get that info to you as soon as possible.
