### ISSUE TITLE
As a user I would like to see statistics on a given project

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/brays#22]
- Number of works
- Number of files
- .... more stats?

**Comment by seanlw** [comment]
Maybe add?: 
* Last modified
* Breakdown of formats

**Comment by amgaynor** [comment]
Those are good additions. For now I think that list of stats will suffice:

- Number of works
- Number of files
- Last modified
- Breakdown of formats

**Comment by seanlw** [comment]
Can you clarify "Number of works", is this number of objects?

**Comment by amgaynor** [comment]
Yes

**Comment by metaweidner** [comment]
Transferred to Trello.
