### ISSUE TITLE
Natural language date display decade and century precision

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/brays#25]
Natural language date display not working for decade and century precision. 

Currently:
 
Input | Output
------|--------
192x | unknown
19xx | unknown

Should be:

Input | Output
------|--------
192x | 1920s
19xx | 1900s

**Comment by seanlw** [comment]
The compatibility comes from this library https://www.npmjs.com/package/edtf.

Use 'X' not 'x' for unknowns.

**Comment by seanlw** [comment]
I'll have to work on displaying century and decade unknowns correctly. Right now the library only replaces them with 'x'.

**Comment by amgaynor** [comment]
Ok sounds good. I think the EDTF spec requires a lowercase 'x': http://www.loc.gov/standards/datetime/pre-submission.html#maskedprecision

**Comment by seanlw** [comment]
Any specification requirements will need to be made to the EDTF project at https://github.com/inukshuk/edtf.js. This is the main library this is used to validate EDTF.
