### ISSUE TITLE
Lag/issue when deleting flags

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/brays#31]
Christin noticed that in the NWC collection, when she deletes the value in the flag note area, she is not able to move to another object in the collection. When I tried to replicate this problem in a test collection of 3 items, I was able to do it without a problem. I'm wondering if this is an issue because of the size of the collection? It works fine if she clicks on the "x" to close the note, but if she deletes the note content, the flag goes away in the lefthand area, but she can't go into another object.

**Comment by seanlw** [comment]
@amgaynor If you are needing to remove a flag, use the 'x'. When that happens can to go to 'View' -> 'Developer' -> 'Toggle Developer Tools' and post a screen cap of that window.

**Comment by amgaynor** [comment]
This is what appears on the error screen. Not sure if this is what you wanted.

![error](https://cloud.githubusercontent.com/assets/15199579/24168751/56fd1bc8-0e49-11e7-9319-6f2bd2c76db3.JPG)

**Comment by seanlw** [comment]
This problem comes up because Brays is being packaged while still in developer mode and it likes to do more checks than needed for production code. I've fixed this for future versions, so this won't be an issue.

Until then if you want to remove a flag, use the 'x' button to remove.
