### ISSUE TITLE
Indicate/move to last edited upon opening

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/brays#32]
When opening a project in Brays, is it possible to open the last item edited or indicate the last item edited? This will help the metadata specialist return to the spot they were last working.

**Comment by seanlw** [comment]
I can if only one person is doing the editing. I can look into how to go about doing that, but it will be at the user level. Meaning that if someone else looks at it, they will be at a different point.

**Comment by amgaynor** [comment]
In our general workflow, only one person is editing a particular collection at a time. One person enters all of the metadata in and then after that, there is a review process where a person may or may not open the collection in Brays. I realize that may not be generalizable to all potential Brays users and it may not even be our workflow forever. If you advise against it, I could just suggest the person flag the last item or record it some other way.

**Comment by seanlw** [comment]
I almost want to say if they really need to know where they last left off, just flag it. I want to avoid having to many indicators and get confused on their meaning. This could just be apart of the workflow instead of being glued into the app.

**Comment by amgaynor** [comment]
Sounds good. Closing this issue.
