### ISSUE TITLE
CONTENTdm Export: Human Readable Date

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/brays#33]
Should Brays should put the humanized version of the EDTF date into the `Date` field and place the EDTF date into a hidden `Date (EDTF)` field? That way the date value will look good for end users and we'll have the original EDTF code in the CDM metadata.

**Comment by seanlw** [comment]
If this is just part of the CDM export, does there need to be a EDTF field at all?

**Comment by metaweidner** [comment]
It all depends on where we're getting the migration metadata for the transition collections. Will we treat it as a new collection and use the original DIP, or will we apply the full CDM legacy collection migration methodology? If it's the former, then we can skip the additional `Date (EDTF)` field and just plug the humanized version into `Date`.

**Comment by seanlw** [comment]
I think treating it as a new collection and use the DIP is the better solution. At this point Brays CDM export can be used for anything, not just for migration reasons.

**Comment by metaweidner** [comment]
Should it then export the humanized date value, or is that too restrictive for general use? Alternatively, we might be able to build in a humanizer for post-processing.

**Comment by seanlw** [comment]
Good question, either way we go has implications on general use I feel like.

**Comment by metaweidner** [comment]
@seanlw Let's do the following with dates in the CDM export:

- human readable date goes into the `Date` column
- encoded date goes into the `Date (EDTF)` column

**Comment by seanlw** [comment]
It should be noted that `Date (EDTF)` will be a CDM export only field; that field will not exist in the MAP.
