### ISSUE TITLE
CONTENTdm Export: File Name

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/brays#34]
It would be great if Brays can create a `File Name` column and plug the file name into it during CDM export.

**Comment by seanlw** [comment]
It does now, just doesn't have a header for it. If this is for metadata should this be apart of the map?

**Comment by metaweidner** [comment]
There will need to be two columns with the file name for CDM ingest:

- `File Name` for metadata display
- `Object File Name` so CDM knows which file to associate with the item

It's an open question as to whether or not we should bake that into Brays or treat it as a post-process. I'm leaning toward not including File Name in the MAP. It seems not very useful for end users.

**Comment by metaweidner** [comment]
On second thought, we may not need the additional `File Name` column for display at all if we're migrating transition collections in the new collection workflow. The last column with the file name will definitely need to have the `Object File Name` header.
