### ISSUE TITLE
CONTENTdm Export: Add Local Rights Statements

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/brays#35]
What is the best way to get the local rights statement language into CONTENTdm?

It might be possible to make those statements available in the MAP: https://github.com/uhlibraries-digital/bcdams-map/blob/gh-pages/_data/elements/rights.yml

Alternatively, it could be a post-process in the project client.

**Comment by seanlw** [comment]
I'm assuming this is the long form statements, beyond what's already in the MAP? I guess my first question would be how would we expect other export modules to look like for other systems (not just Hyku). If it's just for CDM then maybe having it be a post-process thing makes the most since.

**Comment by metaweidner** [comment]
We'll use a post-process CDM find and replace like we did for Rights.
