### ISSUE TITLE
CONTENTdm Export: Preservation ARK

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/brays#38]
Should we export the `pm` ARK to the `Identifier` Field for CDM, or should we create a new field in the MAP according to this approach? https://github.com/uhlibraries-digital/bcdams-map/issues/63

In the first approach, the `pm` ARK will be visible in CDM, and in the second approach we'll have to find a suitable predicate and add the `Preservation Identifier` field to the CDM template, possibly as a hidden field.

The third option is to leave it out of the CDM metadata altogether and only add it when we upload to Hyku.

**Comment by seanlw** [comment]
It makes since to me to at least put it in CDM. If we do that then it will need to be in the MAP so we can use it through the workflow. Harder to implement if we just do it outside the MAP.

**Comment by metaweidner** [comment]
The `pm` ARK will be in the `Preservation Location` column.

**Comment by seanlw** [comment]
Since it's in the MAP, the CDM export will have it automatically.
