### ISSUE TITLE
Brays Freezing while using Autofill function

### ISSUE THREAD

**Issue by christinz** [uhlibraries-digital/brays#42]
While using the auto fill function in Brays, I  selected 3 object that were spread apart (ex: object 003,007, and 010), entered the text for the field i needed populated, and after clicking OK, Brays froze.  After reopening the application, my changes were made though.  This happened twice.

Note: This does not happen when i select multiple objects that are right next to each other (ex: 001,002,003, etc.)

**Comment by christinz** [comment]
@seanlw  Rights

**Comment by seanlw** [comment]
@christinz I'm still trying to reproduce this issue. Next time this happens, in the menu go to 'View' -> 'Developer' -> 'Developer Tools' and provide a screen capture of the new window that appears. Thanks.

**Comment by metaweidner** [comment]
Closed as stale.
