### ISSUE TITLE
Error after CDM Export

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/brays#44]
When a CDM export is processing, the Brays application icon on the taskbar show the progress of the process. After I did a CDM Export, the application icon on the task bar remained 'lit up': 
![image](https://cloud.githubusercontent.com/assets/15199579/24863978/794bfd64-1dc8-11e7-8e2b-bd8cc536d32f.png)
Usually it just goes back to a transparent background. 

I checked the developer tools to see if there was anything and I'm seeing this error message:
![image](https://cloud.githubusercontent.com/assets/15199579/24864029/9e401fd8-1dc8-11e7-8d60-f0f53e6f510c.png)

**Comment by seanlw** [comment]
This is a problem with Electron. I can remove the progress bar altogether if you don't want it to remain. The error displayed is not related to this issue.

**Comment by seanlw** [comment]
I'm going to remove the progress bar since it doesn't work as expected. It was a nice try anyway.
