### ISSUE TITLE
Forward slashes from csv producing error in Brays 

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/brays#51]
Andy created a script that maps metadata from one csv file to a properly formatted Brays csv, but when I try to open that project in Brays, it gives me an error. The forward slashes in the metadata.csv usually seem translate properly in Brays to indicate the file location, but maybe there's something about the data produced from Andy's script that Brays doesn't like? We're also working on Windows machines...
![pasted image at 2017_07_26 04_48 pm](https://user-images.githubusercontent.com/15199579/28674289-98a57f3c-72aa-11e7-805b-f36ac9f8b2d2.png)

**Comment by seanlw** [comment]
What does the csv file look like for the file_path? Brays does not use/store full paths in the csv file.

**Comment by seanlw** [comment]
Forward/Backslashes isn't the the problem since this has been tested and this error would have come up from the very beginning.

**Comment by amgaynor** [comment]
It turns out that the filenames in the metadata.csv didn't match the filenames in the objects folder, so this isn't an issue.
