### ISSUE TITLE
Present warning for invalid vocabulary

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/brays#55]
The application should present the user with a warning when something is wrong with the vocabulary source in Preferences.

**Comment by metaweidner** [comment]
I like the new warning. Is it desired behavior to present the warning when there is no data in the Vocabulary preferences field? Some users may not want/use the controlled vocabulary features.

**Comment by seanlw** [comment]
Makes since. I thought I already had a check in there, obviously not.
