### ISSUE TITLE
Autofill entry UX

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/brays#58]
We want to be able to click anywhere in entire autofill entry line, vs. just clicking on the text that appears in order to fill the metadata field with that value. 

For example, in Subject, you start typing in "do" and so, below, "dogs" and "doors" shows up, if you use the mouse to select the "dogs" option, you have to click on the actual text, vs just clicking somewhere same selection line in order for it to populate the metadata field.

We would like to be able to click anywhere in that line (within the dropdown, not across the whole app at the line, if possible) to populate that value for the metadata field.

**Comment by seanlw** [comment]
Brays is no longer being developed and has been deprecated. You can follow future work with [Mason](https://github.com/uhlibraries-digital/mason)
