### ISSUE TITLE
Duplicate titles appear in navigation pane

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/brays#59]
Duplicate titles displaying in the navigation pane (see image). This doesn't affect the actual metadata but can be confusing.

![image](https://user-images.githubusercontent.com/15199579/59464965-6ef8a580-8def-11e9-95ad-be36e49435d6.png)

**Comment by seanlw** [comment]
Brays is no longer being developed and has been deprecated. You can follow future work with [Mason](https://github.com/uhlibraries-digital/mason)
