### ISSUE TITLE
Vocab not loading after delay opening project

### ISSUE THREAD

**Issue by dulekde** [uhlibraries-digital/brays#60]
![cedar](https://user-images.githubusercontent.com/23407888/60104837-dbe13900-9727-11e9-8910-e10440be46e5.PNG)
Whenever I take more than ~3 minutes to find/choose a project to open in Brays, Cedar will not load.

**Comment by seanlw** [comment]
@dulekde can you send me a snapshot of the developer tools console

**Comment by dulekde** [comment]
![error](https://user-images.githubusercontent.com/23407888/60203119-95680900-9811-11e9-9cc3-46ad77b78855.PNG)
