### ISSUE TITLE
EDTF Date validation

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/brays#7]
Validate https://uhlibraries-digital.github.io/bcdams-map/#date values as EDTF
- http://www.loc.gov/standards/datetime/pre-submission.html
- http://digital2.library.unt.edu/edtf/

**Comment by amgaynor** [comment]
@seanlw @metaweidner Here is the example I mentioned in the stand up: 
https://github.com/duke-libraries/edtf-humanize
